import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: {
    icon: "/FinFetch_Logo.png", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/FinFetch_Logo.png" type="image/png" />
      </head>
      <body className="flex flex-col items-center justify-center min-h-screen bg-gray-50 text-gray-900">
        {children}
      </body>
    </html>
  );
}

